
GPUS: (0,)
OUTPUT_DIR: 'output'
WORKERS: 12
PRINT_FREQ: 30

DATASET:
  TRAIN_SET: './data/small_train/'
  LABEL_SET: './data/small_train_masks/'
  IMG_WIDTH: 240
  IMG_HEIGHT: 160

MODEL:
  FEATURES: [64, 128, 256, 512]

LOSS:

TRAIN:
  BATCH_SIZE_PER_GPU: 16
  SHUFFLE: true
  BEGIN_EPOCH: 0
  END_EPOCH: 100
  LR: 0.0009  # Initial learning rate
  LR_END: 0.0003  # Final learning rate
  LR_FACTOR: 0.25  # for MultiStepLR
  LR_STEP:  # for MultiStepLR
  - 100
  - 150
  - 200
  - 220
  WD: 0.1
  GAMMA1: 0.99
  GAMMA2: 0.0
  MOMENTUM: 0.9
  NESTEROV: false
TEST:

  BATCH_SIZE_PER_GPU: 16
  BBOX_THRE: 1.0
  IMAGE_THRE: 0.0
  IN_VIS_THRE: 0.2
  MODEL_FILE: ./output/xray/transpose_h/TP_H_w48_256x192_d96_h192_relu_enc6_mh1_lr0/final_state.pth
